sqlDB:
  # sqlConnStr: mysql+pymysql://tal:Nikifox2024!@priority-test-dwh.mysql.database.azure.com:3306/
  sqlConnStr: postgresql+psycopg2://talc:Nikifox2024!@priority-erp.postgres.database.azure.com:5432/

mongoDB:
  mongoDbConnStr: mongodb+srv://talcohen0507:Taltool87!@erpdataplatform.t8ot6ep.mongodb.net/test

  metadataDbName: MetadataDB
  configDbName: admin_admin
  configCollectionName: ConfigCollection
  datatypeMappingCollectionName: datatypeMapping
